version: '3.9'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1.23.11
    container_name: Uptime-Kuma
    volumes:
      - ${UPTIMEKUMA_VOLUME_PATH}:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - ${UPTIMEKUMA_PORT}:3001
    restart: always
    mem_limit: 96m
